stages:
  - build
  - test

build_backend:
  stage: build
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd backend
    - chmod u+x ./gradlew
    - ./gradlew build -x test
  artifacts:
    paths:
      - backend/build/libs/*.jar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build_frontend:
  stage: build
  image: node:23-alpine
  tags:
    - students-buildkit-medium
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

   
unit_tests_backend:
  stage: test
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd backend
    - chmod u+x ./gradlew
    - ./gradlew test --tests "course_project.demo.unit.*"
    - find . -name "*.xml"
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/test/**/*.xml 
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
