stages:
  - build
  - test
  - deploy

variables:
  POSTGRES_DB: mydatabase
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: mypassword
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/mydatabase
  SPRING_DATASOURCE_USERNAME: myuser
  SPRING_DATASOURCE_PASSWORD: mypassword
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - postgres:14
  - docker:dind
   
build_backend:
  stage: build
  image: gradle:8.13-jdk17
  tags:
    - students-buildkit-medium
  script:
    - cd backend
    - ./gradlew build -x test
  artifacts:
    paths:
      - backend/build/libs/*.jar
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

build_frontend:
  stage: build
  image: node:23-alpine
  tags:
    - students-buildkit-medium
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

unit_tests_backend:
  stage: test
  image: gradle:8.13-jdk17
  script:
    - cd backend
    - ./gradlew test --tests "course_project.demo.unit.*"
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/**/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

integration_tests_backend:
  stage: test
  image: gradle:8.13-jdk17
  services:
    - postgres:14
  script:
    - cd backend
    - ./gradlew bootRun &
    - sleep 30
    - ./gradlew test --tests "course_project.demo.integration.*"
  artifacts:
    when: always
    reports:
      junit: backend/build/test-results/**/*.xml
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"

deploy:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker-compose up -d --build
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"